
export enum visitedMoviesMutationEnum{
    "UPDATE_DATA"="UPDATE_DATA",
    "CLEAR_DATA"="CLEAR_DATA"
}

export enum visitedMoviesActionEnum{
    "INIT_VISITEDMOVIES_FROM_LOCALSTORAGE"="INIT_VISITEDMOVIES_FROM_LOCALSTORAGE",
    "ADD_MOVIE"="ADD_MOVIE",
    "CLEAR_ALL_MOVIES"="CLEAR_ALL_MOVIES"
}
